language: node_js
sudo: true
dist: trusty
node_js:
- '7.0'
branches:
  only:
  - master
script:
- npm test
- npm run generate
after_success:
- bash deploy-site.sh
env:
  global:
    secure: HQrnsNsWnliYt6lFR3nfJByC2D0sPlTgW3EhlcgLnMDr8o6Bw+eATHXe7VCQFpAyTzJuDeh/jHURnfQ08+dyT/TMCl95+zf+LDM5V3Ki10TY6HYKxfJy2BxbP3jcT0nHPRnkSXpGH2fABwEmqKMIIz5S4WxUjRK4bpct0E+Uf1akEShLNnHcztgpnFZ4M67Vow9AkmIElyXJrUiswYm2xJ1i/bBcba4tI7gCx2WPX75JP7H85H4UjDq2aYjxrjGysVQtTWEHj19CbtGjEpkjeuAikoWxgN5CI3v4zZxT8d+SdALcbR5bmYyvTinNFYZQKJ2gN5kFDl/ufygr97dmTqlUgTtrG68bUQ33EB3gFWJ6L0GWLInsH6Bh2Ppb1ccRfN4EexcIxuMQ9bq/+BXdED3zoNf+ccw5vt5p1Swrbv8gHrWIPnr8ii8XhdzoHi4z7dOnxfDAUP2J3v+wemgIabtxPz3iSzOPPQzzcYYp/MQzRBBC/iwhSFylJqbLyJdU/9OLPXYvRN8qt1O7AVaCZn4uBhCZqlf544hTe08KoNWzkDPLvXlqIA4rBkuEJCADrBOL40p2xRuYwF5GS69u2mvDBD/rTjEDCfhYiDPSv5IstExrr2WOoWSvB63jfAAw/TwMIsSkWDann3oup8giBJxuNuItLKrUSGb19yPjynY=
