language: node_js
node_js:
  - '7.0'
branches:
  only:
    - master
script:
  - npm test
  - npm run-script generate
after_success:
  - bash deploy-site.sh
env:
  global:
    - secure: >-
        gGyiQScm/udC+nhlnmWCtjaRCJ2vWe+yFYLkoaxMRG98HP5d4YU3N0xoJ536bQ+KdzdR30NuQzHiN6FoUGQRBLFKgljAXX0FqFOOd2htolmDLiZKnbTkjJQg4x5SHEgnzHT2xv0IhuQhk5lNdsuTBYA+R85ZbKyUQhmeFTrnzyw1/mVs5iyUGS1peeHfZFvbWv6KotZW06FEOd2hy9BVOy7OfFDluzZFwXbctDJ073+d9QTDlL5ULyzLo+dDttUwN4ADXXEFPB8cSGybelUoE9VOuCxTzsMZ4DD6UOuMFbc/10yvYx67+Q0dU9fR32xgQrFCuVNFfknpuKpDxuWTauNJKqv5RvMuUss7kCtEABcNuLTjTx080uRt4QwIHOQ5oIZbCByjW38uz3cT8PkW09yXO2RAiqmkEnFqs1uli3u63XK6frKOg8XEp8cpRVEgHwtPK6XKCTQOTXtuMXJL1YIuRgmxo/fgEPC4A9ICVVYJPDqFZRqAEL3Ajymnhr7Ig2yBFJDBw/9qHT3hRzna6OaET+Sb5aWYmHPlo4WjDJtiG5BJd3I80rCW8l1RdX2RgisOd0H1rz5L1JMP77M+i0G8fiuVV3W9CzXh9aQJwFRgTUOEM53oSEUmEOJkb8H5/D/lUWnkBFXb8zDcnjWJ+hBLlNPnvFVcuZYEHZmA4/8=
