language: node_js
sudo: true
dist: trusty
node_js:
  - '7.0'
branches:
  only:
    - master
script:
  - npm test
  - npm run-script generate
after_success:
  - bash deploy-site.sh
env:
  global:
    - secure: >-
        LEZRyZazV5HOR1HSuFHTZUxVlVXSqubfL3hQhg02AQ5xfmzOfisvmOG3MZjBzJCBfBI/O8UNYOOaycEoXOlsaHHxgoSlvzIPyneesBJezzAoFTUkJUTdqUvFNHYZyvbdRIDuH1os+jNGfLTo6h6uvXA6I71Be0NE/TW1VIiignInUrvr3j8f44Yk+kC6BJnOjHunAf/tKrAEkGcHViWg9k3XyLyFhPTAbs9YpO6RvbbN5k/U3p+Lfs1IHc85vUz26cIyHlPeWt3ccKPthouDL2HSjgvOs6WF/5B4ocLP8jiD5Lm6yxiC/7Ijc7WAI9qAzv9Dvq5cRQLKBv6qh7lU0jcipgePNRky3J6i/o6RTfZY41g1oRf1dgDJVxiyDJftZXoPe/xvS1BEOgl2kH4hp5Y/j8f09x7Q8g2Fm0vTeJNaaInpKh/cjp/nVndhafY9r93KAwd8tvdNAAl8yyYw7PAfPUxkUzwTsMiA2kCB9TEfRNWArgLw3o3r7ORSWCi0hdZbDFGt6gmWXDtdGanxIzJ3Xk1LdZ+mHjcRF9u89IscOfCq/B7KTOT44urHpsWp8/MMOXhqK6kTGzDktPJwVKzXeBYzP9h4FEsa1GI7UK14b97NPHM05oddieuMlTjCIxcq1ltJyLRgDrMVk78RDNYyeDQOMaRf0HH3HqijoQY=
