language: node_js
sudo: true
dist: trusty
node_js:
  - '7.0'
branches:
  only:
    - master
script:
  - npm test
  - npm run-script generate
after_success:
  - bash deploy-site.sh
env:
  global:
    - secure: >-
        ZFLMmSJwX9/KbiJTI8InQcKt5MUrk5teb+WLfuzIUVFD7C55SXCckIbppXf0be2GZ0I2RHXdHA/WMXQudTTYy0VUnuc94TiRyLL39g6/dgPfCVu+iewRZ1lq2nPlc3k9IQwkh/fG7HtSuEWb3z04RysgmaPdXHDMnUZx3oa7DU0YkGw+tQ1EE5iSe0OlL9DGCxP5pN8/w5tDAQ5x1PfsKKGq6X1zdoE5rlFOFVzojcvp7W/gwbCMsxFK/kTkVfdD1LlellDWccj5vLhnZkOJt+1Nvtrgg/5vYiUKj/ACqMbAqR5/fwzwj+60KjKIYCSTEEql0BLpLO3KWdlUY5Q0Ju/kIG3RV2aLFdtTF2YCkl9UsH4TQMtanlosTgvCI2an+Re7MF8l8dNLbHihbBeZttlpCc59r07qLBBN84IuEoBM0uwqZF7wtQZdPr2DInqHW4mrG4jXKM6iw5Q8TxlOswJ8gf5ISxiG4fc6Yl69XhB+MP4xAqtrDkmE5eWxE7MmbHDZhNTnv6Lgv3GXd4xjy9j6hBInOWzTKbmEmhgUCvEIX+w3XpMH2MAySxlnpOCE8aNIm2hqR4KTRPpWcOrHlpLQSLH4W+ngVXEddhI5YFKbW7jSE1J1RptqXKpS8ZPnjds1drk5Q/7zFShFiO5NZ9WRV6cvGuQ/nGFL0FL7lKw=
