name: publish-site
on:
  push:
    branches:
      - master
jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dcodeIO/setup-node-nvm@master
      - run: npm install
      - run: npm run generate
